name: Package A - Branch deployment

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "packages/package-a/**"
      - "packages/shared/**"
      - "packages/storybook/**"
      - "packages/types/**"
      - "package.json"
      - "**/package-a.yml"

concurrency:
  group: package-a-branch-deploy-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  actions: read
  pull-requests: write

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: 🚛 Checkout
        uses: actions/checkout@v4

      - name: 🪡 Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: 🧶 Install dependencies
        run: bun install

      - name: 🧪 Run unit test
        run: cd packages/package-a && bun run test:ci

      - name: 📃 Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: Package A
          json-summary-path: ./packages/package-a/coverage/coverage-summary.json
          json-final-path: ./packages/package-a/coverage/coverage-final.json
